sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py
    - python: "2.7"
      env: TOXENV=lint
    - python: "3.4"
      env: TOXENV=py
    - python: "3.5"
      env: TOXENV=py
    - python: "3.6"
      env: TOXENV=py
    - python: "3.6"
      env: TOXENV=py36-lint
    - python: "3.7"
      env: TOXENV=py
    # windows testing
    - os: windows
      language: sh
      python: "2.7"
      env: TOXENV=py,lint
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: "3.7"
      env: TOXENV=py,py37-lint
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
cache: pip
install:
  - pip install tox
script:
  - tox
